apiVersion: v2
name: armada
description: |
  Armada is a distributed key-value store. Armada is designed as easy to deploy, kubernetes friendly with emphasis
  on high read throughput and low operational cost.
home: https://armadakv.io
keywords:
- Armada
- database
- key-value
maintainers:
- name: "coufalja"
- name: "jsfpdn"
icon: "https://github.com/armadakv/armada/blob/master/docs/static/armada.png"
kubeVersion: ">= 1.25.0"
type: application
version: 0.1.1
appVersion: "0.1.0"
