{{ if eq "plaintext" .Values.api.tls.mode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "armada.name" . }}-api-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armada.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.api.tls.cert | b64enc }}
  tls.key: {{ .Values.api.tls.key | b64enc }}
{{- else if eq "auto" .Values.api.tls.mode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "armada.name" . }}-api-cert
  labels:
    {{- include "armada.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- $altNames := list ( printf "%s.%s" (include "armada.name" .) .Release.Namespace ) ( printf "%s.%s.svc" (include "armada.name" .) .Release.Namespace ) -}}
  {{- $ca := genCA "armada-ca" 365 -}}
  {{- $cert := genSignedCert ( include "armada.name" . ) nil $altNames 365 $ca }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end}}

