{{- if .Values.maintenance.enabled }}
{{- if eq .Values.maintenance.token.secretKind "plaintext" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "armada.name" . }}-maintenance-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armada.labels" . | nindent 4 }}
data:
  token: {{ .Values.maintenance.token.value | b64enc }}
{{- end }}
{{- if eq .Values.maintenance.token.secretKind "sealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "armada.name" . }}-maintenance-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armada.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.maintenance.token.value }}
{{- end }}
{{- end }}
