apiVersion: v1
kind: Service
metadata:
  name: {{ template "armada.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "armada.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "armada.selectorLabels" . | nindent 6 }}
  ports:
  - name: raft
    targetPort: raft
    port: {{ .Values.raft.port }}
    protocol: UDP
  - name: https
    targetPort: https
    port: {{ .Values.api.port }}
  - name: http-metrics
    targetPort: http-metrics
    port: {{ .Values.metricsPort }}
  publishNotReadyAddresses: true
